apiVersion: v1
kind: Service
metadata:
  name: litellm-proxy-service
  namespace: openwebui-system
spec:
  selector:
    app: litellm-proxy
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
  type: LoadBalancer