apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-proxy
  namespace: openwebui-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm-proxy
  template:
    metadata:
      labels:
        app: litellm-proxy
    spec:
      containers:
      - name: litellm-proxy
        image: ghcr.io/berriai/litellm:main-latest
        ports:
        - containerPort: 4000
        volumeMounts:
        - mountPath: "/app"
          name: config-volume
        args: ["--config", "/app/config.yaml", "--detailed_debug"]
      volumes:
      - name: config-volume
        configMap:
          name: litellm-config 