apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv
  namespace: openwebui-system
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ollama-data" 