apiVersion: v1
kind: PersistentVolume
metadata:
  name: openwebui-pv
  namespace: openwebui-system
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data" 