apiVersion: v1
kind: Service
metadata:
  name: openwebui-service
  namespace: openwebui-system
spec:
  selector:
    app: openwebui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer 